<!-- JAVASCRIPT CODE -->
<script type="text/javascript">
function card() {
	document.getElementById("card").style.display ="block";
	document.getElementById("info").style.display ="none";
	document.getElementById("history").style.display ="none";
	document.getElementById("card-tab").setAttribute("class","card-tab-selected");
	document.getElementById("info-tab").setAttribute("class","card-tab");
	document.getElementById("history-tab").setAttribute("class","card-tab");
}
function info() {
	document.getElementById("card").style.display ="none";
	document.getElementById("info").style.display ="block";
	document.getElementById("history").style.display ="none";
	document.getElementById("card-tab").setAttribute("class","card-tab");
	document.getElementById("info-tab").setAttribute("class","card-tab-selected");
	document.getElementById("history-tab").setAttribute("class","card-tab");
}
function history() {
	document.getElementById("card").style.display ="none";
	document.getElementById("info").style.display ="none";
	document.getElementById("history").style.display ="block";
	document.getElementById("card-tab").setAttribute("class","card-tab");
	document.getElementById("info-tab").setAttribute("class","card-tab");
	document.getElementById("history-tab").setAttribute("class","card-tab-selected");
}
</script>
<!-- CARD INFORMATION AND IMAGE -->
<div style="position:relative; min-height:430px; width:100%; padding:10px;">
	<!-- TEXT CONTAINER -->
	<div style="position:absolute; min-height:430px; margin-top:0; right:0; left:320px;">
			<span class="card-title">{{cardname}}</span><br>
			<span class="card-subtitle">{{SUBTITLE}}</span>
			<div class="card-status {{status}}" title="{{status}}"></div>

		<!-- CONTAINERS FOR DATA CONTROLLED BY TABS: only one should be visible at a time. -->
		<div id="card" class="card-infobox" style="display:block"> <!-- CARD TAB -->
			{{ALL_FIELDS}}
		</div>
		<div id="info" class="card-infobox" style="display:none"> <!-- INFO TAB -->
			<table class="noborder">
				<tr><td>Author:</td><td>{{author}}</td></tr>
				<tr><td>Latest Revision:</td><td>{{date}}</td></tr>
				<tr><td>Who Promoted:</td><td>(NYI){{WHO_PROMOTED}}</td></tr>
			</table>
		</div>
		<div id="history" class="card-infobox" style="display:none"> <!-- HISTORY TAB -->
			{{HISTORY}}
		</div>

		<!-- CONTAINER FOR TABS -->
		<div class="card-tab-line">
			Version {{id}}:{{revision}}
			<a href="index.php?act=delete_card&id={{id}}"><div class="card-tab" style="right:360px; display:{{ADMIN}};">delete</div></a><!-- ONLY DISPLAY IF ADMIN -->
			<a href="index.php?act=edit_card&id={{id}}"><div class="card-tab" style="right:300px; display:{{DEVELOPER}};">edit</div></a><!-- ONLY DISPLAY IF DEV OR UP -->
			<!--translations stuff here--><a href="index.php?act=translate_card&id={{id}}"><div class="card-tab" style="right:240px;">translate</div></a>
			<a href="javascript:card()"><div id="card-tab" class="card-tab-selected" style="right:180px;">card</div></a>
			<a href="javascript:info()"><div id="info-tab" class="card-tab" style="right:120px;">info</div></a>
			<a href="javascript:history()"><div id="history-tab" class="card-tab" style="right:60px;">history</div></a>
		</div>
	</div>
	<!-- IMAGE CONTAINER -->
	<div style="position:absolute; height:430px; width:310px;">
		<img style="width:100%;" src="{{IMAGE_FILENAME}}"></img><br>
	</div>
</div>

<table class="comment">
{{COMMENTS}}
</table>

